server:
  port: 8021
  context-path: /

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://bj-cdb-h6itkdpq.sql.tencentcdb.com:63137/moxi?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root1234
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
   thymeleaf:
    cache: false







