server:
  port: 8021
  context-path: /

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${MYSQL_URL}/moxi?useUnicode=true&characterEncoding=UTF-8
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
   jpa:
     hibernate.ddl-auto: update
     show-sql: false
   thymeleaf:
    cache: false







