spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.210.157:3306/supply
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083
  context-path: /supply